### ISSUE TITLE
Warn in console

### ISSUE THREAD

**Issue by Restland** [Geolykt/EnchantmentsPlus#119]
I get this warn kinda frequently
[15:53:14 WARN]: 	at enchantments-plus.jar//de.geolykt.enchantments_plus.CustomEnchantment.applyForTool(CustomEnchantment.java:328)
[15:53:14 WARN]: 	at enchantments-plus.jar//de.geolykt.enchantments_plus.evt.WatcherEnchant.onBlockBreak(WatcherEnchant.java:105)
[15:53:14 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor600.execute(Unknown Source)
[15:53:14 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[15:53:14 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:53:14 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:53:14 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[15:53:14 WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:400)
[15:53:14 WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:354)
[15:53:14 WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:314)
[15:53:14 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1762)
[15:53:14 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[15:53:14 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[15:53:14 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[15:53:14 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:53:14 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[15:53:14 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[15:53:14 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[15:53:14 WARN]: 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[15:53:14 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[15:53:14 WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[15:53:14 WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[15:53:14 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[15:53:14 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[15:53:14 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[15:53:14 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[15:53:14 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Geolykt** [comment]
Could you also give the line that is above this wall of text?

**Comment by Restland** [comment]
![image](https://user-images.githubusercontent.com/84740054/161396389-5ea9f92c-4caa-4cc9-847d-4bb6afd4cb6f.png)

**Comment by Geolykt** [comment]
Seems straightforward to deal with

**Comment by Restland** [comment]
any action I have to do?

**Comment by Geolykt** [comment]
Not really - I do not know what causes this anyways. I'll fix it in a sec however

**Comment by Restland** [comment]
https://pastebin.com/CSYbbysm
huge tps drops with those

**Comment by Geolykt** [comment]
Do you know which block produces this issue by any chance?

**Comment by Restland** [comment]
Nope, it happens randomly, it spams the console with it till TPS drop down to 9 and then stops
